package enums;

public enum TelegramState {
    ACCEPTING_LANGUAGE,
    ACCEPTING_RESTAURANT_CHOICE,
    ACCEPTING_MENU_OR_CANCEL_BUTTON,
    ACCEPTING_CATEGORY_CHOICE_AND_SENDING_DISHES,
    ACCEPTING_FOOD_CHOICE_GIVE_FULL_INFO_ABOUT_IT,
    ACCEPTING_COUNTER_BUTTONS,
    START
}
